### ISSUE TITLE
Add glossary

### ISSUE THREAD

**Issue by quang-huynh** [Blue-Matter/salmonMSE#2]
@carrieholt @brendanmichaelconnors @catarinawor

Based on the AHA guide and Withler Res Doc, I added the glossary of terms and corresponding variable names to be used in the frontend: https://github.com/Blue-Matter/salmonMSE/blob/master/inst/glossary.csv

Can you comment on the best terminology to use for DFO?

**Comment by carrieholt** [comment]
Yes these labels make sense. A few comments (or do you want to add them directly into the csv?)
-Suggestion to label SAR Smolt-to-Adult Recruit survival.
-The two Beverton-holt models are included to represent spawner-to-adult relationship and spawner-to-smolt relationship but I think only the spawner-to-smolt is used in the population model. Marine (natural) survival is usually assumed to be density-independent (modelled with SAR).  
-Suggesting adding p_(NOS), p_(HOS) and p_(HOB). 
-We do not need to include the parameters for ocean survival, juvenile fish passage, and adult fish passage, as these pertain to hydro-power, which is not a major threat/ management lever for salmon in BC. SAR captures survival from smolts to adult recruitment.
-While we may need to include hatchery systems with both yearling and subyearling releases (so may be good to include now), to start with let’s consider 100% of one or the other.
-The percentage the returns to hatchery vs natural spawning: For most of Canadian hatcheries, spawners return entirely to natural spawning grounds. We can keep the possibility of returning to a fishway in the hatchery, but should set to 0% for now.
-Also suggest adding effective p_(HOS), which accounts for the relative reproductive success of hatchery-origin spawners called -p_(HOSeff) (Withler et al. 2018, Eq 4 in main text). PNI should be calculated from p_(NOB) and effective p_(HOS). 
-I think we need a theta_(hatch) and theta_(nat) for optimum phenotypic trait value in both hatchery and natural environments. Same for pnat.
-RelLoss_i, is calculated in part from the proportion of fitness loss that is assigned to each life stage (often, but not always assumed to be 0.5 for both freshwater and marine life stages). We should add that proportion.

**Comment by quang-huynh** [comment]
Still need to add the last two bullet points
